# Generated by Django 2.1.5 on 2019-01-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_auto_20190124_0044'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='date_init',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.Sala'),
        ),
    ]
