# Generated by Django 2.1.5 on 2019-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20190127_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date_init',
            field=models.DateTimeField(null=True),
        ),
    ]
