# Generated by Django 2.1.5 on 2019-01-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190127_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
