# Generated by Django 4.0.6 on 2022-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190128_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='created_by',
            field=models.CharField(default='anonimo', max_length=100, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='creator_email',
            field=models.EmailField(default='teste@teste.com', max_length=254, verbose_name='Email de quem criou'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de término'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='date_init',
            field=models.DateTimeField(null=True, verbose_name='Data/Hora de início'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
