# Generated by Django 4.0.6 on 2022-07-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('agenda', '0005_agenda_created_by_agenda_creator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='creator_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamento.department', verbose_name='Departamento de quem criou'),
        ),
    ]
