# Generated by Django 4.0.6 on 2022-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agenda_creator_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de segurança'),
        ),
    ]
