# Generated by Django 4.0.6 on 2022-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agenda_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='Código de segurança'),
        ),
    ]
