# Generated by Django 4.0.6 on 2022-07-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_agenda_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='repeat',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Reunião periódica'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='repeat_weekday',
            field=models.CharField(blank=True, choices=[(0, 'segunda-feira'), (1, 'terça-feira'), (2, 'quarta-feira'), (3, 'quinta-feira'), (4, 'sexta-feira'), (5, 'sábado')], max_length=13, null=True),
        ),
    ]
