# Generated by Django 4.0.6 on 2022-07-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_alter_agenda_repeat_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='last_same_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.agenda', verbose_name='Última reunião desta mesma'),
        ),
    ]
