# Generated by Django 4.0.6 on 2022-07-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agenda_last_same_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='last_same_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agenda', verbose_name='Última reunião desta mesma'),
        ),
    ]
