# Generated by Django 4.0.6 on 2022-07-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_remove_periodicagenda_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicagenda',
            name='time_end',
            field=models.TimeField(default='00:00:00', verbose_name='Hora de término'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodicagenda',
            name='time_init',
            field=models.TimeField(default='00:00:00', verbose_name='Hora de início'),
            preserve_default=False,
        ),
    ]
