# Generated by Django 4.0.6 on 2022-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_periodicagenda_time_end_periodicagenda_time_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='must_repeat',
            field=models.BooleanField(default=False, verbose_name='Reunião se repete?'),
        ),
    ]
