# Generated by Django 2.1.5 on 2019-01-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='name',
            new_name='nome',
        ),
    ]
