# Generated by Django 2.1.5 on 2019-01-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_auto_20190124_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='nome',
            new_name='name',
        ),
    ]
