# Generated by Django 2.1.5 on 2019-01-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_auto_20190124_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
