# Generated by Django 4.0.6 on 2022-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_auto_20190127_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
