# Generated by Django 4.0.6 on 2022-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0006_sala_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
