# Generated by Django 4.0.6 on 2022-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_alter_sala_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='empresa',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GPB', 'GPB'), ('GBL', 'GBL'), ('GS', 'GS')], max_length=100, verbose_name='Empresa'),
        ),
    ]
